/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SignupLazyImport = createFileRoute('/signup')()
const SigninLazyImport = createFileRoute('/signin')()
const ProfileLazyImport = createFileRoute('/profile')()
const JournalLazyImport = createFileRoute('/journal')()
const EmotionsLazyImport = createFileRoute('/emotions')()
const EmergencyLazyImport = createFileRoute('/emergency')()
const ChatLazyImport = createFileRoute('/chat')()
const BookLazyImport = createFileRoute('/book')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))

const SigninLazyRoute = SigninLazyImport.update({
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const JournalLazyRoute = JournalLazyImport.update({
  path: '/journal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/journal.lazy').then((d) => d.Route))

const EmotionsLazyRoute = EmotionsLazyImport.update({
  path: '/emotions',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/emotions.lazy').then((d) => d.Route))

const EmergencyLazyRoute = EmergencyLazyImport.update({
  path: '/emergency',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/emergency.lazy').then((d) => d.Route))

const ChatLazyRoute = ChatLazyImport.update({
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/chat.lazy').then((d) => d.Route))

const BookLazyRoute = BookLazyImport.update({
  path: '/book',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/book.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/book': {
      preLoaderRoute: typeof BookLazyImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      preLoaderRoute: typeof ChatLazyImport
      parentRoute: typeof rootRoute
    }
    '/emergency': {
      preLoaderRoute: typeof EmergencyLazyImport
      parentRoute: typeof rootRoute
    }
    '/emotions': {
      preLoaderRoute: typeof EmotionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/journal': {
      preLoaderRoute: typeof JournalLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      preLoaderRoute: typeof SigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  BookLazyRoute,
  ChatLazyRoute,
  EmergencyLazyRoute,
  EmotionsLazyRoute,
  JournalLazyRoute,
  ProfileLazyRoute,
  SigninLazyRoute,
  SignupLazyRoute,
])

/* prettier-ignore-end */
